name: Build and Validate TextEditor
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
    - name: Build with Maven
      run: mvn clean package
    - name: Validate PNG
      run: file screenshots/*.png | grep PNG
    - name: Upload JAR
      uses: actions/upload-artifact@v3
      with:
        name: TextEditor-JAR
        path: target/TextEditor-1.0-SNAPSHOT.jar
